framework:
    # default_locale: de
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    enabled_locales: ['de', 'nl', 'en']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de
        providers:
